spring.application.name=management

spring.datasource.url=jdbc:mysql://viaduct.proxy.rlwy.net:31858/railway
spring.datasource.username=root
spring.datasource.password=wXwVBAfkTgmFCKOFjfxRMpJVYxFVIrSD

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.root=INFO
logging.level.com.inventory.management=DEBUG

logging.file.name=logs/stockflow.log

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%level] - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n

server.port=${PORT:8080}